version: '3.8'

services:
  da: #this is Celestia's light client
    build:
      context: .
      dockerfile: ./Dockerfile.da
    ports:
      - "26650:26650"
      - "26659:26659"
    command: [ "bash", "./da-entrypoint" ]
    env_file:
      - networks/${CONDUIT_NETWORK:?set network}/.env
      - .env
  geth: # this is Optimism's geth client
    build: 
      context: .
      dockerfile: ./Dockerfile.celestia
    ports:
      - 8545:8545       # RPC
      - 8546:8546       # websocket
      - 30303:30303     # P2P TCP (currently unused)
      - 30303:30303/udp # P2P UDP (currently unused)
      - 7301:6060       # metrics
    command: [ "bash", "./geth-entrypoint" ]
    env_file:
      - .env.default
      - networks/${CONDUIT_NETWORK:?set network}/.env
      - .env
    volumes:
      #- ./geth-data/:/data # enable to have persistency between restarts
      - ./networks/${CONDUIT_NETWORK:?set network}/genesis.json:/genesis.json
  node:
    build:
      context: . 
      dockerfile: ./Dockerfile.celestia
    depends_on:
      - geth
    ports:
      - 7545:8545     # RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
      - 7300:7300     # metrics
      - 6060:6060     # pprof
    command: [ "bash", "./op-node-entrypoint.celestia.sh" ]
    env_file:
      - .env.default
      - .env.default.celestia
      - networks/${CONDUIT_NETWORK:?set network}/.env
      - .env
    volumes:
      - ./networks/${CONDUIT_NETWORK:?set network}/rollup.json:/rollup.json
      - ./networks/${CONDUIT_NETWORK:?set network}/genesis.json:/genesis.json
